{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ae098a90",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Total samples in dataset: 19533\n",
      "Available emotions: ['sentimental' 'afraid' 'proud' 'faithful' 'terrified' 'joyful' 'angry'\n",
      " 'sad' 'jealous' 'grateful' 'prepared' 'embarrassed' 'excited' 'annoyed'\n",
      " 'lonely' 'ashamed' 'guilty' 'surprised' 'nostalgic' 'confident' 'furious'\n",
      " 'disappointed' 'caring' 'trusting' 'disgusted' 'anticipating' 'anxious'\n",
      " 'hopeful' 'content' 'impressed' 'apprehensive' 'devastated']\n",
      "Dataset columns: ['conv_id', 'situation', 'emotion', 'conversations']\n",
      "Filtered samples (joyful + sad): 1269\n",
      "Number of conversations: 1269\n",
      "Joyful conversations: 602\n",
      "Sad conversations: 667\n",
      "Saved data/empathetic_dialogues.csv with 1269 rows.\n",
      "\n",
      "Sample conversations:\n",
      "          conv_id emotion                                          situation  \\\n",
      "0    hit:3_conv:7  joyful  I am very happy to have been first over 300 st...   \n",
      "1   hit:5_conv:10     sad  One year during christmas, i did not get a sin...   \n",
      "2   hit:7_conv:15     sad  I got recently got three rejection letters for...   \n",
      "3  hit:14_conv:29  joyful  I was so happy when I moved in to my new home....   \n",
      "4  hit:22_conv:45     sad  I felt sad when my dog passed away. It was a p...   \n",
      "\n",
      "                                        conversation  \n",
      "0  Hi, this year, I was the first over 300 studen...  \n",
      "1  During christmas a few years ago, I did not ge...  \n",
      "2  People get rejected all the time but it should...  \n",
      "3  Planning out my new home has turned out to be ...  \n",
      "4  Have you ever had a pet that you had to put do...  \n",
      "\n",
      "Sample conversation text:\n",
      "Emotion: joyful\n",
      "Conversation: Hi, this year, I was the first over 300 students at my enginering school Sounds great! So what's your major? It is computer science. I am very happy of this achievement and my family is very proud. We...\n"
     ]
    }
   ],
   "source": [
    "from datasets import load_dataset\n",
    "import pandas as pd\n",
    "import os\n",
    "\n",
    "def preprocess():\n",
    "    # Load empathetic dialogues dataset from HuggingFace\n",
    "    dataset = load_dataset(\"Estwld/empathetic_dialogues_llm\")\n",
    "\n",
    "    # Convert the 'train' split to pandas DataFrame\n",
    "    df_train = dataset[\"train\"].to_pandas()\n",
    "    \n",
    "    print(f\"Total samples in dataset: {len(df_train)}\")\n",
    "    print(f\"Available emotions: {df_train['emotion'].unique()}\")\n",
    "    print(f\"Dataset columns: {list(df_train.columns)}\")\n",
    "\n",
    "    # Filter dataset for only Joyful and Sad emotions (correct emotion names)\n",
    "    df_filtered = df_train[df_train[\"emotion\"].isin([\"joyful\", \"sad\"])]\n",
    "    print(f\"Filtered samples (joyful + sad): {len(df_filtered)}\")\n",
    "\n",
    "    # Extract conversations from the conversations column and combine into full dialogue\n",
    "    processed_conversations = []\n",
    "    \n",
    "    for _, row in df_filtered.iterrows():\n",
    "        # Extract all dialogue turns from the conversations list\n",
    "        full_dialogue = []\n",
    "        for turn in row['conversations']:\n",
    "            full_dialogue.append(turn['content'])\n",
    "        \n",
    "        # Join all dialogue turns into one text\n",
    "        combined_text = \" \".join(full_dialogue)\n",
    "        \n",
    "        processed_conversations.append({\n",
    "            'conv_id': row['conv_id'],\n",
    "            'emotion': row['emotion'],\n",
    "            'situation': row['situation'],\n",
    "            'conversation': combined_text  # Full dialogue as one text\n",
    "        })\n",
    "    \n",
    "    # Convert to DataFrame\n",
    "    conversations_df = pd.DataFrame(processed_conversations)\n",
    "    \n",
    "    print(f\"Number of conversations: {len(conversations_df)}\")\n",
    "    print(f\"Joyful conversations: {len(conversations_df[conversations_df['emotion'] == 'joyful'])}\")\n",
    "    print(f\"Sad conversations: {len(conversations_df[conversations_df['emotion'] == 'sad'])}\")\n",
    "\n",
    "    # Create data directory if it doesn't exist\n",
    "    os.makedirs(\"data\", exist_ok=True)\n",
    "    \n",
    "    # Save to CSV file in data/ directory\n",
    "    conversations_df.to_csv(\"data/empathetic_dialogues.csv\", index=False)\n",
    "    print(\"Saved data/empathetic_dialogues.csv with\", len(conversations_df), \"rows.\")\n",
    "    \n",
    "    # Display sample data\n",
    "    print(\"\\nSample conversations:\")\n",
    "    print(conversations_df.head())\n",
    "    \n",
    "    # Show a sample conversation text\n",
    "    print(\"\\nSample conversation text:\")\n",
    "    if len(conversations_df) > 0:\n",
    "        print(f\"Emotion: {conversations_df.iloc[0]['emotion']}\")\n",
    "        print(f\"Conversation: {conversations_df.iloc[0]['conversation'][:200]}...\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    preprocess()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
